version: '3.5'

services:
  client:
    build:
      context: .
      target: client-base
    command: 'yarn start'
    ports:
      - 3000:3000
    volumes:
      - ./client/package.json:/app/package.json
      - ./client/src:/app/src

  server:
    build:
      context: .
      target: server-base
    command: 'yarn start'
    ports:
      - 4000:4000
    volumes:
      - ./client/src/shared:/app/src/shared
      - ./server/package.json:/app/package.json
      - ./server/src:/app/src
      - ./server/data:/app/data
